on:
  pull_request:
    branches: [main]

jobs:
  test-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Echo pom
        run: cat pom.xml
        shell: bash

